### ISSUE TITLE
Which one is the "vsftpd" client that is available on the Debian 9 "Stretch" APT repository?

### ISSUE THREAD

**Issue by martijintro** [InfrastructureServices/vsftpd#2]
Hi there

Which one is the "vsftpd" client that is available on the Debian 9 "Stretch" APT repository?

I have some questions regarding that software!

- https://github.com/dagwieers/vsftpd
- https://github.com/djarosz/vsftpd
- https://github.com/InfrastructureServices/vsftpd

(???)

I'm really really confused - so thank you for your feedback.

**Comment by msehnout** [comment]
Hi, none of them. There is no upstream git repository for vsftpd. This is the upstream website: https://security.appspot.com/vsftpd.html
